### ISSUE TITLE
[review] Global peer review

### ISSUE THREAD

**Issue by dewarian** [sjagoori/functional-programming#3]
## Global scan throughout the repository

- [x] **Contains a description**
  * The repository does not have about description yet. Please keep it simple, for example, your student information and information about the course. Or just about the project.
- [x] **Contains a readme** 
  * The repository has a simple but understanding readme, describes the use case, a short description, installation, possible sources, and a GPLv3 license.
- [x] **Contains a license**
- [x] **Contains a .gitignore** 
  * The repository contains a gitignore generated by GitHub.  There are no node_modules or dirty junk.
- [x] **Concept described in the readme?**
  * The _in short_ section contains information globally over the project but not about the specific concept.
- [x]  Plagiarism and acknowledgments
  * None to be found; you have commented which documentation you have used from next.js 

### Assessment
Documentation is on the minimal side as the concept is lacking. Add your main research question as that would tie into the _in short_ section.

## Wiki
- [x] **Does the wiki contain a debrief?**
  * It contains a debrief, which explains who the partner is and what we will be doing throughout the course. It also describes the freedom the students have within the theme.
- [x] **Data cleaning / transformation process described?**
  * [exploring data](https://github.com/sjagoori/functional-programming/wiki/Exploring-data) wiki page describes Shabier's data process sanitizing with the survey data.
  * The page starts with Shabier's research questions and the required data to visualize that question. It may be wise to move this to its own wiki page and later link it within the readme.
  * There is a typo in the [title](https://github.com/sjagoori/functional-programming/wiki/Exploring-data#santization-examples); it misses an I after san.
  * Described the data sanitization process with survey data, Starting with the eye color as an example.
  * Used code snippets wisely to show code pieces and the output of the code.
    * Code is adequately written and on par with his experience with programming.
  * Used regex to minimize chaining to convert RGB to HEX.
  * Kept functions pure and properly used a functional pattern throughout the code examples.
- [x] **Described which functional patterns are applied?**
  * There are no functional patterns described or mentioned.
    * This could be fixed by creating a new wiki page about the theory of functional programming and patterns used within, such as factories, currying, first-class functions, and more. 
      * Maybe also interesting to know what the other programming paradigms are?
- [x] **Do I see improvement? (where should I see improvement?)**
Not applicable.

#### Assessment
A clear process of how Shabier went through the cleaning process of the survey data. Nice touch of how you have used regex.

## Code 
- [x] **Can I understand the code flow?**
  *  Code Flow within [exploring data[(https://github.com/sjagoori/functional-programming/wiki/Exploring-data#santization-examples) is concise and structured clearly.
- [x] **Is the most important code at the top?**
   * Import is at top and most important function right under it.
- [x] **Is everything split into functions? Are other principles of FP applied?**
   * functions are split into its individual task.
   * RDW Nextjs app is simplistic; it loads and filters the data based on the license plate and create a list view.
   * Why are there two API calls? in [index.js](https://github.com/sjagoori/functional-programming/blob/86552f3e0b25fcbba36d769ed2e660c2182c7aac/pages/index.js#L20) and [a separate folder named API](https://github.com/sjagoori/functional-programming/blob/master/pages/api/hello.js)
- [x] **Are ```map``` / ```ForEach``` used correctly?**
  * map and forEach are used in their respective manner.
- [x] **Check code quality (Is it functional, consistency, reusability, naming conventions, etc.).**
Yes.

#### Assessment
One would think you really want to develop a full-blown react application with the RDW data.
I think you belong to one of the more experienced developers in this course.

**Comment by sjagoori** [comment]
_Why are there two API calls? in index.js and a separate folder named API_

The project contains files after generation- will remove these in next update

**Comment by dewarian** [comment]
> _Why are there two API calls? in index.js and a separate folder named API_
> 
> The project contains files after generation- will remove these in next update

👍
